---
- hosts: localhost
  sudo: yes
  vars:
    home: /home/pbassiner
  tasks:
   - name: Install base packages
     apt: pkg={{ item }} state=installed update_cache=true
     with_items:
      - vim
      - zsh
      - terminator
   - name: Symlink dotfiles
     file: path={{ home }}/.{{ item }} src={{ home }}/.dev-env/dotfiles/{{ item }} state=link
     with_items:
      - gitconfig
      - zshrc
   - include: java-oracle.yml