---
- hosts: localhost
  sudo: yes
  tasks:
   - name: Install base packages
     apt: pkg={{ item }} state=installed update_cache=true
     with_items:
      - vim
      - zsh
      - terminator
   - include: java-oracle.yml