---
- hosts: localhost
  tasks:
   - include: apt.yml
   - include: deb-packages.yml
   - include: targz-apps.yml
#   - include: atom-plugins.yml
   - include: java-oracle.yml
   - include: sdkman.yml
   - name: Install JVM development tools using sdkman
     script: sdkman.sh
   - include: oh-my-zsh.yml
   - name: Symlink oh-my-zsh themes
     file: path={{ home }}/.oh-my-zsh/themes/{{ item }} src={{ home }}/.dev-env/zsh/{{ item }} state=link
     with_items:
      - custom.zsh-theme
   - name: Set zsh as default sh
     become: yes
     shell: "chsh -s $(which zsh) {{ username }}"
   - name: Symlink dotfiles
     file: path={{ home }}/.{{ item }} src={{ home }}/.dev-env/dotfiles/{{ item }} state=link force=yes
     with_items:
      - gitconfig
      - zshrc
      - aliases
   - name: Create config folders
     file: path={{ home }}/.config/{{ item }} state=directory
     with_items:
      - terminator
   - name: Symlink config files
     file: path={{ home }}/.config/{{ item }} src={{ home }}/.dev-env/config/{{ item }} state=link force=yes
     with_items:
      - terminator/config